name: Jev Issue comment evaluation

on:
  issue_comment:
    types: [created]

permissions:
  actions: read
  contents: read
  issues: write

jobs:
  evaluate:
    if: >-
      github.event.repository.owner.type == 'Organization' &&
      github.repository == 'roccho-org/envs' &&
      github.event.issue.number == 52 &&
      github.event.comment.body == '/jev-evaluate' &&
      github.event.issue.pull_request == null
    uses: roccho-org/ops/.github/workflows/jev-issue-comment.yml@dcb66f2906fb0a092bdcf36aaabb192dff144d5f
    secrets:
      JEV_API_KEY: ${{ secrets.JEV_API_KEY }}
